GET  http://localhost:5023/api/movies
content-type: application/json

###
GET  http://localhost:5023/api/users
content-type: application/json

###

GET  http://localhost:5023/api/users/1
content-type: application/json

###

POST http://localhost:5023/api/users
content-type: application/json

{  
  "firstname": "ahmed",
  "lastname": "inerzaf",
  "email": "hamid@example.com",
  "city": "maroco",
  "language": "Chleuh",
  "password": "kirikou78130"
}
 
###

POST http://localhost:5023/api/login
Content-type: application/json

{
  "email": "hamid@example.com",
  "password": "kirikou78130"
}

####

POST http://localhost:5023/api/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImlhdCI6MTY4NzQyNzc0MiwiZXhwIjoxNjg3NDMxMzQyfQ.kAiLF05L1qHMflCVPioGZtbi3ytW_M0Q6TOb6iSXcf4
Content-type: application/json

{

  "title": "La ligne verte 3",
  "director": "jec 3 ",
  "year": "2000",
  "color": "purple",
  "duration": 3333
}

####

POST http://localhost:5023/api/movies
Content-type: application/json

{

  "title": "La ligne verte 3",
  "director": "jec 3 ",
  "year": "2000",
  "color": "purple",
  "duration": 444444
}


